apiVersion: 1

datasources:
  - name: DPP PostgreSQL
    uid: dpp-postgres
    type: postgres
    access: proxy
    url: postgres:5432
    user: ${POSTGRES_USER}
    secureJsonData:
      password: ${POSTGRES_PASSWORD}
    jsonData:
      database: ${POSTGRES_DB}
      sslmode: disable
      postgresVersion: 1800
      timescaledb: false
    isDefault: true
    editable: false
